Add job to buid and push containers to registry.
Add base_image parameter requesting only a specific base container
version to be built, i.e. "ubuntu:22.04".

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -7,6 +7,9 @@ on:
       test_tag:
         description: 'Optional tag name to simulate release'
         required: false
+      base_image:
+        description: 'Container version to test (e.g. "alpine:3.21")'
+        required: false
 
 env:
   CTEST_OUTPUT_ON_FAILURE: ON
@@ -20,6 +23,142 @@ permissions:
   contents: read
 
 jobs:
+  generate-matrix:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Generate matrix from Dockerfiles
+      id: set-matrix
+      run: |
+        if [ -n '${{ github.event.inputs.base_image }}' ]
+        then
+          FLT="grep -w ${{ github.event.inputs.base_image }}"
+        else
+          FLT="cat"
+        fi
+        BASE_IMAGES="`grep "^ARG BASE_IMAGE" dockerfiles/*/Dockerfile | \
+         ${FLT} | \
+         awk -F= '{print $2}' | sort -u | \
+         ./misc/get-arch-buildargs fltimages | \
+         jq -R . | jq -s . | tr '\n' ' '`"
+        if [ ! -n "${BASE_IMAGES}" -o "${BASE_IMAGES}" = "[]" ]
+        then
+          if [ -n '${{ github.event.inputs.base_image }}' ]
+          then
+            echo "BASE_IMAGES generation failed" >&2
+          else
+            echo "${{ github.event.inputs.base_image }} not found"
+          fi
+          exit 1
+        fi
+        echo "matrix=${BASE_IMAGES}" >> $GITHUB_OUTPUT
+
+  Docker:
+    name: Build&Push to Registry
+    needs: generate-matrix
+    runs-on: ubuntu-latest
+    permissions:
+      packages: write
+    strategy:
+      fail-fast: false
+      matrix:
+        base_image: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
+    env:
+      DOCKER_RW: ${{ ( github.repository == 'ccache/ccache' && github.event_name != 'pull_request' ) && 'true' || 'false' }}
+      GHCR_REPO: ghcr.io/${{ github.repository_owner }}/ccache
+      BASE_IMAGE: ${{ matrix.base_image }}
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+      with:
+        submodules: 'recursive'
+
+    - name: Set up QEMU
+      id: qemu
+      uses: docker/setup-qemu-action@v3
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+
+    - name: Login to GitHub Container Registry
+      if: env.DOCKER_RW == 'true'
+      uses: docker/login-action@v3
+      with:
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Set dynamic environment
+      run: |
+        GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+        test "${GIT_BRANCH}" != "master" || GIT_BRANCH="latest"
+        OS_TAG="`echo ${{ env.BASE_IMAGE }} | sed 's|.*/||g ; s|:|-|g ; s|_|-| ; s|_|.|'`"
+        PLATFORMS="`docker manifest inspect ${{ env.BASE_IMAGE }} | \
+          jq -r '.manifests[] | "\(.platform.os)/\(.platform.architecture)\(if .platform.variant != null then "/\(.platform.variant)" else "" end)"' | \
+          sort -u | ./misc/get-arch-buildargs fltplatforms | paste -sd ','`"
+        if [ ! -n "${PLATFORMS}" ]
+        then
+          echo "Cannot get list of platforms supported by the ${{ env.BASE_IMAGE }}." >&2
+          exit 1
+        fi
+        BUILD_IMAGE="${{ env.GHCR_REPO }}:${GIT_BRANCH}-${OS_TAG}"
+        if [ "${{ github.event_name }}" != 'pull_request' ]; \
+        then \
+          CACHE_IMAGE="${BUILD_IMAGE}"; \
+        else
+          CACHE_IMAGE="${{ env.GHCR_REPO }}:master-${OS_TAG}"; \
+        fi
+        CACHE_SPEC="type=registry,ref=${CACHE_IMAGE}-buildcache"
+        docker manifest inspect ${CACHE_IMAGE} >/dev/null 2>/dev/null || CACHE_IMAGE="scratch"
+        echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
+        echo "PLATFORMS=${PLATFORMS}" >> $GITHUB_ENV
+        echo "OS_TAG=${OS_TAG}" >> $GITHUB_ENV
+        echo "BUILD_IMAGE=${BUILD_IMAGE}" >> $GITHUB_ENV
+        echo "CACHE_IMAGE=${CACHE_IMAGE}" >> $GITHUB_ENV
+        echo "CACHE_SPEC=${CACHE_SPEC}" >> $GITHUB_ENV
+        cat dockerfiles/Dockerfile.pref dockerfiles/${OS_TAG}/Dockerfile \
+          dockerfiles/Dockerfile.build > Dockerfile
+
+    - name: Build & Push image
+      if: env.DOCKER_RW == 'true'
+      uses: docker/build-push-action@v6
+      with:
+        context: .
+        file: ./Dockerfile
+        build-args: |
+          BASE_IMAGE=${{ env.BASE_IMAGE }}
+          CACHE_IMAGE=${{ env.CACHE_IMAGE }}
+          CMAKE_PARAMS=-DSTATIC_LINK=ON
+          INSTALL_PREFIX=/usr
+          GCC_APT=gcc
+        tags: ${{ env.BUILD_IMAGE }}
+        platforms: ${{ env.PLATFORMS }}
+        push: true
+        outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Multi-arch ccache for ${{ env.OS_TAG  }}
+        cache-from: ${{ env.CACHE_SPEC }}
+        cache-to: ${{ env.CACHE_SPEC }},mode=max
+
+    - name: Build image (PR)
+      if: env.DOCKER_RW != 'true'
+      uses: docker/build-push-action@v6
+      with:
+        context: .
+        file: ./Dockerfile
+        build-args: |
+          BASE_IMAGE=${{ env.BASE_IMAGE }}
+          CACHE_IMAGE=${{ env.CACHE_IMAGE }}
+          CMAKE_PARAMS=-DSTATIC_LINK=ON
+          INSTALL_PREFIX=/usr
+          GCC_APT=gcc
+        platforms: ${{ env.PLATFORMS }}
+        cache-from: ${{ env.CACHE_SPEC }}
+
   build_and_test:
     timeout-minutes: 30
     env:
